### ISSUE TITLE
Requests not returned

### ISSUE THREAD

**Issue by matsawyer** [jkingyens/dockerthon#8]
Hi jkingyens,

Thank you very much for building this awesome repo.

I've synced up my client and server builds, but when trying to build the tests (I receive the blah blah blah output) and run them to make an images, in the second terminal I am returned 

docker: Error: request returned Not Found for API route and version http://localhost:3000/v1.24/containers/create, check if the server supports the requested API version.

When going into the server file, it looks like I'm having trouble with this function, 
app.post('/v1.24/images/create', function (req, res)

This is what is returned in the `npm start` terminal:

```POST /v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=sample-ios-app&ulimits=null HTTP/1.1``` 

```200 - "```

```-" "Docker-Client/1.12.5 (darwin)"
{ Hostname: '',
  Domainname: '',
  User: '',
  AttachStdin: false,
  AttachStdout: true,
  AttachStderr: true,
  Tty: false,
  OpenStdin: false,
  StdinOnce: false,
  Env: [],
  Cmd: null,
  Image: 'sample-ios-app',
  Volumes: {},
  WorkingDir: '',
  Entrypoint: null,
  OnBuild: null,
  Labels: {},
  HostConfig: 
   { Binds: null,
     ContainerIDFile: '',
     LogConfig: { Type: '', Config: {} },
     NetworkMode: 'default',
     PortBindings: {},
     RestartPolicy: { Name: 'no', MaximumRetryCount: 0 },
     AutoRemove: false,
     VolumeDriver: '',
     VolumesFrom: null,
     CapAdd: null,
     CapDrop: null,
     Dns: [],
     DnsOptions: [],
     DnsSearch: [],
     ExtraHosts: null,
     GroupAdd: null,
     IpcMode: '',
     Cgroup: '',
     Links: null,
     OomScoreAdj: 0,
     PidMode: '',
     Privileged: false,
     PublishAllPorts: false,
     ReadonlyRootfs: false,
     SecurityOpt: null,
     UTSMode: '',
     UsernsMode: '',
     ShmSize: 0,
     ConsoleSize: [ 0, 0 ],
     Isolation: '',
     CpuShares: 0,
     Memory: 0,
     CgroupParent: '',
     BlkioWeight: 0,
     BlkioWeightDevice: null,
     BlkioDeviceReadBps: null,
     BlkioDeviceWriteBps: null,
     BlkioDeviceReadIOps: null,
     BlkioDeviceWriteIOps: null,
     CpuPeriod: 0,
     CpuQuota: 0,
     CpusetCpus: '',
     CpusetMems: '',
     Devices: [],
     DiskQuota: 0,
     KernelMemory: 0,
     MemoryReservation: 0,
     MemorySwap: 0,
     MemorySwappiness: -1,
     OomKillDisable: false,
     PidsLimit: 0,
     Ulimits: null,
     CpuCount: 0,
     CpuPercent: 0,
     IOMaximumIOps: 0,
     IOMaximumBandwidth: 0 },
  NetworkingConfig: { 
     EndpointsConfig: {}
    } 
}
{}
::1 - - [11/Jan/2017:01:35:32 +0000] 

"POST /v1.24/containers/create HTTP/1.1" 404 - "

-" "Docker-Client/1.12.5 (darwin)" 

```

Would you have any suggestions for how to fix this?

Thanks,
Mat #

**Comment by newlight77** [comment]
Hi matsawyer,

I've updated all endpoint version from '/v1.18' to '/v1.30', as per today, and 'iphonesimulator8.3' to 'iphonesimulator10.3'. I then open the project with xcode so it converts source code because of swift version complaining. The image is built successfully. 

However, I can't run the container, having the error below:


$ docker run test
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4055598]

goroutine 1 [running]:
github.com/docker/cli/cli/command/container.runContainer(0xc4201f7980, 0xc42036bef0, 0xc4203b7400, 0xc42000c740, 0x4f68880, 0xc42006e050)
	/go/src/github.com/docker/cli/cli/command/container/run.go:171 +0xa62
github.com/docker/cli/cli/command/container.runRun(0xc4201f7980, 0xc4200a3560, 0xc42036bef0, 0xc4203b7400, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:94 +0x141
github.com/docker/cli/cli/command/container.NewRunCommand.func1(0xc4203cdb00, 0xc4204384d0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:48 +0x109
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203cdb00, 0xc4200720e0, 0x1, 0x1, 0xc4203cdb00, 0xc4200720e0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203b4240, 0xc4203b46c0, 0xc4203be0b0, 0xc4200864b0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203b4240, 0xc4203b4240, 0x4f6a880)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:168 +0xc3
```


$ docker ps
`json: cannot unmarshal object into Go struct field Container.State of type strin`

**Comment by matsawyer** [comment]
@newlight77 
After you successfully build the image, 
(use `docker build --no-cache .` in the project directory )
can you take the container name response and run a docker start on that container name?

Let me know what is returned by that and if the container shows up with `docker ps -a`

**Comment by newlight77** [comment]
Same results as above

```
✔ ~/wks/src/github/clones/docker4xcode/sample [master L|✚ 1…4]
08:05 $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED                  SIZE
test-build          latest              4fcdbbbb7d09        Less than a second ago   17.9MB
test                latest              c8c47653d5cb        Less than a second ago   17.3MB
✔ ~/wks/src/github/clones/docker4xcode/sample [master L|✚ 1…4]
08:05 $ docker run test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4055598]

goroutine 1 [running]:
github.com/docker/cli/cli/command/container.runContainer(0xc4201db980, 0xc4203c0030, 0xc42039b400, 0xc420454200, 0x4f68880, 0xc420014110)
	/go/src/github.com/docker/cli/cli/command/container/run.go:171 +0xa62
github.com/docker/cli/cli/command/container.runRun(0xc4201db980, 0xc42008d4d0, 0xc4203c0030, 0xc42039b400, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:94 +0x141
github.com/docker/cli/cli/command/container.NewRunCommand.func1(0xc4203afb00, 0xc420416550, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:48 +0x109
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203afb00, 0xc420010200, 0x1, 0x1, 0xc4203afb00, 0xc420010200)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420398240, 0xc4203986c0, 0xc4203a0130, 0xc42000e4a0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420398240, 0xc420398240, 0x4f6a880)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:168 +0xc3
✘-2 ~/wks/src/github/clones/docker4xcode/sample [master L|✚ 1…4]
08:05 $ docker ps -a
json: cannot unmarshal object into Go struct field Container.State of type string
✘-1 ~/wks/src/github/clones/docker4xcode/sample [master L|✚ 1…4]
```

**Comment by matsawyer** [comment]
I never opened the project with xCode or converted the project source code to run within xCode (I've been attempting to hack it together inside a linux distro) 

& I have not been able yet to reproduce your error, so looking at that last segment of output

```
json: cannot unmarshal object into Go struct field Container.State of type string
✘-1 ~/wks/src/github/clones/docker4xcode/sample [master L|✚ 1…4]
```

Would you want to try going into the file and matching up the JSON string type to the struct field container type and see if fix progress is made?  

-- IE match type String & String || Container & Container

**Comment by newlight77** [comment]
Hi matsawyer,

I came to the same conclusion. Digging into json matching isn't an easy task. 

The need I had is to automate tests of an IOS app using docker, as all of our automated tests, except IOS app representing less than 5% of our test set, run inside a dockerized environnement. So I put this aside for now.

**Comment by matsawyer** [comment]
_Closing as stale issue_ 🥯🍞🥖
